### ISSUE TITLE
Class 'phpDocumentor\Reflection\DocBlockFactory' not found

### ISSUE THREAD

**Issue by shakaran** [googleads/googleads-php-lib#168]
Related with issue #145 in experimental branch:

```
PHP Fatal error:  Uncaught Error: Class 'phpDocumentor\Reflection\DocBlockFactory' not found in myproject/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsNormalizer.php:85
Stack trace:
#0 myproject/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/BatchJobs/v201607/BatchJobs.php(75): Google\AdsApi\AdWords\AdWordsNormalizer->__construct(NULL, Object(Google\AdsApi\AdWords\BatchJobs\DotRemoverNameConverter))
#1 myproject/index.php(179): Google\AdsApi\AdWords\BatchJobs\v201607\BatchJobs->__construct()
#2 {main}
  thrown in myproject/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsNormalizer.php on line 85
```

It seems that the dependency phpdocumentor is not added in composer.json:

```
composer require phpdocumentor/phpdocumentor
```

Running that command doesn't solve for me the bug, so, I don't know how to autoload that.

**Comment by shakaran** [comment]
The right package missing seems to be:

    composer require phpdocumentor/reflection-docblock

**Comment by fiboknacky** [comment]
We'll fix this soon.

**Comment by vtsao** [comment]
Fixed with https://github.com/googleads/googleads-php-lib/releases/tag/25.0.0.
