### ISSUE TITLE
DateError.INVALID_STRING_DATE_TIME 

### ISSUE THREAD

**Issue by hiakong** [googleads/googleads-php-lib#234]
when I run the example code that UploadOfflineConversions.php , then occur the below errors.  What is the right "CONVERSION_TIME" ? 
then I use the below  date string ,then error also.
 "2017-02-8 13:00:00+0500" 、 
"2017-02-8 13:00:00 America/Los_Angeles"、  
So,How is the right date string? thanks

Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201609\cm\ApiException' with message 'DateError.INVALID_STRING_DATE_TIME @ ; trigger:'2017-02-08 13:00:00 America/Los_Angeles'' in /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:39 Stack trace: #0 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array) #1 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(162): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', 'DateError.INVAL...') #2 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(126): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault)) #3 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201609/cm/OfflineConversionFeedService.php(88): Google\AdsApi\Common\AdsSoapClient->__soapCal in /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 39

**Comment by hiakong** [comment]
https://developers.google.com/adwords/api/docs/appendix/codes-formats#date-and-time-formats   I have fix it , sorry

**Comment by hiakong** [comment]
https://developers.google.com/adwords/api/docs/appendix/codes-formats#date-and-time-formats  ,I use the time like '20170209 145008  Asia/Shanghai' but the error is occur
