### ISSUE TITLE
DateError.INVALID_STRING_DATE_TIME

### ISSUE THREAD

**Issue by hiakong** [googleads/googleads-php-lib#235]
when I run the example code that UploadOfflineConversions.php , then occur the below errors. What is the right "CONVERSION_TIME" ?  thank you !

Fatal error: Uncaught exception 'Google\AdsApi\AdWords\v201609\cm\ApiException' with message 'DateError.INVALID_STRING_DATE_TIME @ ; trigger:'20170209 145008 Asia/Shanghai'' in /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:39 Stack trace: #0 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array) #1 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(162): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', 'DateError.INVAL...') #2 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(126): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault)) #3 /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201609/cm/OfflineConversionFeedService.php(88): Google\AdsApi\Common\AdsSoapClient->__soapCall('mutat in /home/wwwroot/default/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php on line 39

**Comment by hiakong** [comment]
https://developers.google.com/adwords/api/docs/appendix/codes-formats#date-and-time-formats ,I use the time like '20170209 145008 Asia/Shanghai' but the error is occur

**Comment by hiakong** [comment]
Could you tell me how to solve it , I want to use the api to send  Conversions  to adwords.

**Comment by fiboknacky** [comment]
Hello @hiakong 

As far as I know, your date time (`20170209 145008 Asia/Shanghai`) is correctly formatted. 
So I don't know why the error is thrown here too. 

As this is not directly related to PHP client library, could you please reach out to [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) for proper investigation?
In this way, we can communicate privately, if necessary, to ask your account ID, etc. for deeper investigation.

Best,
Knack

**Comment by fiboknacky** [comment]
Hi @hiakong 

Glad to hear that you could fix this.
I'll close this bug soon if you don't have further questions about this.

Feel free to open a bug in the future if an issue is related to the PHP client library or reach out to [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api) for general AdWords API questions. :-)

Best,
Knack
