### ISSUE TITLE
PHP Fatal error. Help me with configuration

### ISSUE THREAD

**Issue by PgrNascimento** [googleads/googleads-php-lib#260]
Hi,

I follow the steps, and get this error. I update my php version, enable SSL, cURL and SOAP but returned this error yet.

How to proceed ?

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 51: SSL: certificate verification failed (result: 5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187
Stack trace:
#0 /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /Users/alan/workspace/php/adwords/vendor/guz in /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187

Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 51: SSL: certificate verification failed (result: 5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187

GuzzleHttp\Exception\RequestException: cURL error 51: SSL: certificate verification failed (result: 5) (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187

Call Stack:
    0.0010     378616   1. {main}() /Users/alan/workspace/php/adwords/GetCampaings.php:0
    0.0531     684032   2. Google\AdsApi\Examples\AdWords\v201702\BasicOperations\GetCampaigns::main() /Users/alan/workspace/php/adwords/GetCampaings.php:91
    0.1362    1560704   3. Google\AdsApi\Examples\AdWords\v201702\BasicOperations\GetCampaigns::runExample() /Users/alan/workspace/php/adwords/GetCampaings.php:87
    0.1878    2031584   4. Google\AdsApi\AdWords\v201702\cm\CampaignService->get() /Users/alan/workspace/php/adwords/GetCampaings.php:53
    0.1878    2032336   5. Google\AdsApi\Common\AdsSoapClient->__soapCall() /Users/alan/workspace/php/adwords/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201702/cm/CampaignService.php:156
    0.1878    2032336   6. Google\AdsApi\AdWords\AdWordsHeaderHandler->generateHttpHeaders() /Users/alan/workspace/php/adwords/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:86
    0.1878    2032336   7. Google\AdsApi\Common\Util\OAuth2TokenRefresher->getOrFetchAccessToken() /Users/alan/workspace/php/adwords/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsHeaderHandler.php:72
    0.1878    2032336   8. Google\Auth\Credentials\UserRefreshCredentials->fetchAuthToken() /Users/alan/workspace/php/adwords/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php:60
    0.1879    2032336   9. Google\Auth\OAuth2->fetchAuthToken() /Users/alan/workspace/php/adwords/vendor/google/auth/src/Credentials/UserRefreshCredentials.php:92
    0.2082    2604200  10. Google\Auth\HttpHandler\Guzzle6HttpHandler->__invoke() /Users/alan/workspace/php/adwords/vendor/google/auth/src/OAuth2.php:492
    0.2082    2604256  11. GuzzleHttp\Client->send() /Users/alan/workspace/php/adwords/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php:34
    1.5594    2707240  12. GuzzleHttp\Promise\RejectedPromise->wait() /Users/alan/workspace/php/adwords/vendor/guzzlehttp/guzzle/src/Client.php:104
```

**Comment by fiboknacky** [comment]
Hello @PgrNascimento 

To confirm, you've followed the steps to install the libs using composer as listed [here](https://github.com/googleads/googleads-php-lib#getting-started), right?
Could you please clarify what you've put in the `adsapi_php.ini`?

Thanks!
Knack

**Comment by PgrNascimento** [comment]
Hi @fiboknacky

I tried do the guide again, but when I  try get the refresh token, the
return is the same error.

I know it's a problem with my computer/configuration, but you can I help
me? I don't know what I do

Thanks!

2017-03-24 12:44 GMT-03:00 Thanet Knack Praneenararat <
notifications@github.com>:

**Comment by fiboknacky** [comment]
Hi @PgrNascimento 

Sure. I'm here to help, but first, could you please clarify what you've put in `adsapi_php.ini`?
Without this information, I have no ideas what can cause this error.

Best,
Knack

**Comment by PgrNascimento** [comment]
So fast

Thank you @fiboknacky

There is my `adsapi_php.ini`
```
[ADWORDS]
; Required AdWords API properties. Details can be found at:
;
https://developers.google.com/adwords/api/docs/guides/basic-concepts#soap_and_xml
developerToken = "jieJJ_lLDdOGbviHq9tebQ"
clientCustomerId = "423-414-5766"

; Optional. Set a friendly application name identifier.
 userAgent = "DDWB"

; Optional additional AdWords API settings.
; endpoint = "https://adwords.google.com/"
; isPartialFailure = false

; Optional setting for utility usage tracking in the user agent in requests.
; Defaults to true.
; includeUtilitiesInUserAgent = true

[ADWORDS_REPORTING]
; Optional reporting settings.
; isSkipReportHeader = false
; isSkipColumnHeader = false
; isSkipReportSummary = false
; isUseRawEnumValues = false

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case. See the README for guidance:
;
https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

; For installed application or web application flow.
 clientId = "
916267657699-1ckkksqp4d40fjiotam52tierarnju5n.apps.googleusercontent.com"
 clientSecret = "sX-RSI1JjyBQ3bo9LrWW7ka5"
 refreshToken = "1/7sf_JxSGasgFyntl9vD9CKOS3K2qBZkHISDvSNwM8bw"

; For service account flow.
; jsonKeyFilePath = "INSERT_ABSOLUTE_PATH_TO_OAUTH2_JSON_KEY_FILE_HERE"
; scopes = "https://www.googleapis.com/auth/adwords"
; impersonatedEmail = "INSERT_EMAIL_OF_ACCOUNT_TO_IMPERSONATE_HERE"

[SOAP]
; Optional SOAP settings. See SoapSettingsBuilder.php for more information.
; compressionLevel = <COMPRESSION_LEVEL>
; wsdlCache = <WSDL_CACHE>

[PROXY]
; Optional proxy settings to be used by SOAP requests.
; host = "<HOST>"
; port = <PORT>
; user = "<USER>"
; password = "<PASSWORD>"

[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
; soapLogLevel = "INFO"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
; batchJobsUtilLogLevel = "INFO"

```

2017-03-24 15:54 GMT-03:00 Thanet Knack Praneenararat <
notifications@github.com>:

**Comment by fiboknacky** [comment]
Hi @PgrNascimento 

I should have asked you to remove your developer tokens and other sensitive information.
I removed your comment but rest assure that I have your info already and will have a look at it later.

Best,
Knack

**Comment by fiboknacky** [comment]
And could you tell your PHP version + OS?
Is the information in[ this line](https://github.com/googleads/googleads-php-lib/blob/5eea2f7fb65fd07f0413eb2e33bc2e7563c43078/src/Google/AdsApi/Common/AdsSoapClientFactory.php#L160) relevant to you?

**Comment by PgrNascimento** [comment]
Oh, my bad.

I will have more attention. Answering your question: My php version is 7.0.15 and my OS is OSX El Capitan 10.11.6

**Comment by hakimio** [comment]
@PgrNascimento Like fibonacky already suggested you are missing CA certificates. They have to be defined using "curl.cainfo" config in your "php.ini" file.

**Comment by PgrNascimento** [comment]
Hi guys,

The problem was with SSL Version in my php. I changed and it worked.

Thank you for help me!

If somebody has same problem, I followed this tutorial: 

* https://www.farces.com/wikis/naked-server/php/php-openssl/

* Restarted my apache 

* Restarted my terminal
