### ISSUE TITLE
Exception: ManagedCustomerServiceError.MAC_ERROR 

### ISSUE THREAD

**Issue by vovan47** [googleads/googleads-php-lib#336]
Hi @fiboknacky 
I've just got the following exception for a first time:
`[ManagedCustomerServiceError.MAC_ERROR @ ]`

Trace:
```
#0 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
#1 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(162): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', Array)
#2 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(126): Google\AdsApi\Common\AdsSoapClient->parseApiExceptionFromSoapFault(Object(SoapFault))
#3 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201705/mcm/ManagedCustomerService.php(103): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array)
#4 xxx.php(71): Google\AdsApi\AdWords\v201705\mcm\ManagedCustomerService->get(Object(Google\AdsApi\AdWords\v201705\cm\Selector))
```
Can you give any clue what does it mean?

**Comment by fiboknacky** [comment]
Hello Vladimir,

That error doesn't look familiar to me.
Could you please post your question on the [AdWords API Forum](https://groups.google.com/forum/#!forum/adwords-api)?

Best,
Knack

**Comment by vovan47** [comment]
Hi Knack, thanks for answer! Yeah I've posted there simultaneously :)
Looks like a problem of backend, not your library.

**Comment by fiboknacky** [comment]
Yep, thanks for reporting anyway. I'll close this.
