### ISSUE TITLE
What are requirements for poxy server to coop with Google AdWordsAPI library?

### ISSUE THREAD

**Issue by sebastianpiskorski** [googleads/googleads-php-lib#382]
I'm dealing with very restrictive proxy server, where I have to use credentials and all traffic is blocked by default. Administrator can unlock certain domains for me but I have to list them for him. So far he had unlocked for me following domains:

- *.1e100.net
- *.google.de
- *.google.com
- *.googleapis.com

but still, when I try to connect with examples I get error:

```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to 2a00:1450:4016:80c::200a: Network is unreachable (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Han in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186
```

My configuration for proxy is set in `adsapi_php.ini` file in home folder. All other options like "refreshToken" or "developerToken" are also set.

Is there a way to force library to use `*.1e100.net` instead of IPv6 `2a00:1450:4016:80c::200a:` addresses.

**Comment by fiboknacky** [comment]
Hi @sebastianpiskorski 

Could you please specify what you've put in `adsapi_php.ini`?
From what you stated above, it looks like you're trying to whitelist connections between your computers and our servers at the same time?

Best,
Knack

**Comment by sebastianpiskorski** [comment]
Here is my `adsapi_php.ini`.
```
[ADWORDS]
; Required AdWords API properties. Details can be found at:
; https://developers.google.com/adwords/api/docs/guides/basic-concepts#soap_and_xml
developerToken = "developer-token_A"
clientCustomerId = "some_number-some_hash.apps.googleusercontent.com"

; Optional. Set a friendly application name identifier.
; userAgent = "INSERT_USER_AGENT_HERE"

; Optional additional AdWords API settings.
endpoint = "https://adwords.google.com/"
; isPartialFailure = false

; Optional setting for utility usage tracking in the user agent in requests.
; Defaults to true.
; includeUtilitiesInUserAgent = true

[ADWORDS_REPORTING]
; Optional reporting settings.
; isSkipReportHeader = false
; isSkipColumnHeader = false
; isSkipReportSummary = false
; isUseRawEnumValues = false

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case. See the README for guidance:
; https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

; For installed application or web application flow.
clientId = "111-222-3333"
clientSecret = "some_secret-some_suffix"
refreshToken = "1/some_token-some_suffix"

; For service account flow.
; jsonKeyFilePath = "INSERT_ABSOLUTE_PATH_TO_OAUTH2_JSON_KEY_FILE_HERE"
; scopes = "https://www.googleapis.com/auth/adwords"
; impersonatedEmail = "INSERT_EMAIL_OF_ACCOUNT_TO_IMPERSONATE_HERE"

[SOAP]
; Optional SOAP settings. See SoapSettingsBuilder.php for more information.
compressionLevel = 9
wsdlCache = "Off"

[PROXY]
; Optional proxy settings to be used by SOAP requests.
host = "proxy.domain.address.com"
port = 1234
user = "proxy_user"
password = "proxy_password"

[LOGGING]
; Optional logging settings.
soapLogFilePath = "/tmp/soap.log"
soapLogLevel = "DEBUG"
reportDownloaderLogFilePath = "/tmp/report-downloader.log"
reportDownloaderLogLevel = "DEBUG"
batchJobsUtilLogFilePath = "/tmp/bjutil.log"
batchJobsUtilLogLevel = "DEBUG"
```

**Comment by fiboknacky** [comment]
Hello,

First, it looks like you're using `clientId` with `clientCustomerId` wrongly. Please swap them.
However, it's not related to this issue, I think.


> From what you stated above, it looks like you're trying to whitelist connections between your computers and our servers at the same time?

Could you please answer my second question too? Are you trying to whitelist the connections?
From what you said, it seems you'd like to allow connections from *.google.com (+ `*.1e100.net`), but in another place, you stated that you'd like to put that in the proxy section of `adsapi_php.ini`, which seems not quite correct to me.
What's put in that section is rather a proxy server that can process your requests.

Best,
Knack

**Comment by sebastianpiskorski** [comment]
1. Do not try to put domains in [PROXY] section of `adsapi_php.ini` I want to know why do I get such error. From what is written in error message, lib tries to connect with some server using IPv6 address instead of domain name. Addresses belong to `*.1e100.net` domain namespace. So I'm interested if the library could be forced not to use Ipv6 addresses.

2. Yes I'm trying to whitelist connections between my server and google servers. There is a proxy between and by default all conections are denied, until whitelisted. Only domain names could be whitelisted.

3. At the moment proxy is configured to whitelist connections for following domains:

```
*.1e100.net
*.google.de
*.google.com
*.googleapis.com
```

4. From reverse DNS lookup I could find that all IPv6 addresses belong to `*.1e100.net`

**Comment by sebastianpiskorski** [comment]
What I cannot understand is why lib wants to connect to `*.1e100.net` addresses. All I should whitelist should be `adwords.google.com` and `*.googleapis.com` for OAuth2 authentication.

What do you mean by `would be a reverse lookup that the requests go through once requests reach the AdWords API servers`, I think that i don't understand this part or I understand it in a wrong way.

**Comment by dklimkin** [comment]
@sebastianpiskorski any chance you are using BatchJobService?

Can you check the proxy logs for the full URLs of these requests?

**Comment by sebastianpiskorski** [comment]
@dklimkin Not explicitly, unless it is used by the lib "under the hood". I use the lib to get the list of Campaigns and download reports for selected campaigns.

On the account, I use, there are few hundreds of campaigns.

**Comment by dklimkin** [comment]
@sebastianpiskorski Actually, Dorian is correct on the thread Thanet linked. What happens is:

1. The library gets IP addresses for adwords.google.com:
$ dig adwords.google.com
[...]
adwords.l.google.com.   299     IN      A       74.125.206.139

2. The lib connects to the server using IP address 74.125.206.139.
3. The proxy does a reverse lookup to identify if the domain is allowed:
$ dig -x 74.125.206.139
[...]
139.206.125.74.in-addr.arpa. 3600 IN    PTR     wk-in-f139.1e100.net.

so you see *.1e100.net, which is a google domain.

One way to disable IPv6 can be to do it for the whole box, e.g. like described in this article. If you don't use IPv6, it might be easier to do it once for all apps:
  https://www.techrepublic.com/article/how-to-disable-ipv6-on-linux/

Another one is to hack into lib code and add force_ip_resolve option:
  http://docs.guzzlephp.org/en/stable/request-options.html#force-ip-resolve

Generally, IPv6 is a good thing and my recommendation would be to work with your network administrator to support it. Otherwise, you can use one of the workaround provided, but I don't feel it's something we want in the general distribution.

**Comment by fiboknacky** [comment]
I close this to inactivity. Please let us know if you have further issues.

**Comment by sebastianpiskorski** [comment]
@fiboknacky @dklimkin  I have disabled IPv6 on a server and now I got a different error, without IPv6 address `cURL error 7: Failed connect to www.googleapis.com:443; Operation now in progress.`. Infrastructure owner says I don't use proxy properly, but the only option I have is to configure lib. I did run an example `GetCampaigns` with and without proxy configured and I have different curl errors. I made sure that proper config file is used. Lib example was run outside any application.

Is it possible that GoogleAds lib somehow ignores proxy config?

Here is the output with and then without proxy configured:
```
[user@server.com examples]$ php -f AdWords/v201705/BasicOperations/GetCampaigns.php --no-chdir
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed connect to www.googleapis.com:443; Operation now in progress (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /home/user/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /home/user/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/user/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/user/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/wg in /home/user/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

[user@server.com examples]$ vi ~/adsapi_php.ini //disabling proxy config

[user@server.com examples]$ php -f AdWords/v201705/BasicOperations/GetCampaigns.php --no-chdir
PHP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl"
 in /home/user/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 65
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201705/CampaignService?wsdl"
 in /home/user/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:65
Stack trace:
#0 /home/user/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(65): SoapClient->SoapClient('https://adwords...', Array)
#1 /home/user/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201705/cm/CampaignService.php(145): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array)
#2 [internal function]: Google\AdsApi\AdWords\v201705\cm\CampaignService->__construct(Array)
#3 /home/user/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(39): ReflectionClass->newInstanceArgs(Array)
 in /home/user/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 65
```

**Comment by fiboknacky** [comment]
Hello @sebastianpiskorski 

First, you may want to troubleshoot what happened even when you turn proxy off.

**Comment by sebastianpiskorski** [comment]
@fiboknacky I think that I've found a bug in lib. When HttpHandler [$httpHandler = HttpHandlerFactory::build();](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php?utf8=%E2%9C%93#L498) is created to process the OAuth call, the proxy configuration is not passed to that handler.

After injecting this proxy configuration inline, the script start to work as intended.

**Comment by fiboknacky** [comment]
Hello @sebastianpiskorski 

That part you mention resides in the google-auth-php lib, not in this library.
Could you please specify more how you use this library to connect to that one?
In [this line](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php#L63), it should use a proxy HTTP handler created in [this file](https://github.com/googleads/googleads-php-lib/blob/4308d6b03f7ded643fe78b0f2ae0dfa416a62f3e/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php#L63).

Best,
Knack

**Comment by sebastianpiskorski** [comment]
I'm running an example file with `php -f AdWords/v201705/BasicOperations/GetCampaigns.php  --no-chdir` I could provide a backtrace if it helps.

**Comment by fiboknacky** [comment]
Yes please.
And could you please provide your code snippet and the part where you said you inject the proxy config inline too.

Thank you!

**Comment by sebastianpiskorski** [comment]
@fiboknacky Here is backtrace:
```
#0  Google\Auth\OAuth2->fetchAuthToken() called at [/var/app/vendor/google/auth/src/Credentials/UserRefreshCredentials.php:92]
#1  Google\Auth\Credentials\UserRefreshCredentials->fetchAuthToken() called at [/var/app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php:60]
#2  Google\AdsApi\Common\Util\OAuth2TokenRefresher->getOrFetchAccessToken(Google\Auth\Credentials\UserRefreshCredentials Object ([] => Google\Auth\OAuth2 Object ([] => ,[] => GuzzleHttp\Psr7\Uri Object ([] => https,[] => ,[] => www.googleapis.com,[] => ,[] => /oauth2/v4/token,[] => ,[] => ),[] => ,[] => part1-part2.apps.googleusercontent.com,[] => other_token-other_token_suffix,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => 3600,[] => ,[] => ,[] => 1/some_token-some_hash,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => Array ()))) called at [/var/app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsHeaderHandler.php:63]
#3  Google\AdsApi\AdWords\AdWordsHeaderHandler->generateHttpHeaders(Google\AdsApi\AdWords\AdWordsSession Object ([] => token_A,[] => unknown,[] => https://adwords.google.com/,[] => Google\Auth\Credentials\UserRefreshCredentials Object ([] => Google\Auth\OAuth2 Object ([] => ,[] => GuzzleHttp\Psr7\Uri Object ([] => https,[] => ,[] => www.googleapis.com,[] => ,[] => /oauth2/v4/token,[] => ,[] => ),[] => ,[] => part1-part2.apps.googleusercontent.com,[] => other_token-other_token_suffix,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => 3600,[] => ,[] => ,[] => 1/some_token-some_hash,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => Array ())),[] => Google\AdsApi\Common\SoapSettings Object ([] => 9,[] => 0,[] => some.proxy.domain,[] => 12345,[] => some_proxy_user,[] => some_proxy_pass,[] => 1,[] => ),[] => customer_id,[] => ,[] => ,[] => 1,[] => Google\AdsApi\AdWords\ReportSettings Object ([] => ,[] => ,[] => ,[] => ,[] => ),[] => Monolog\Logger Object ([] => AW_SOAP,[] => Array ([0] => Monolog\Handler\StreamHandler Object ([] => ,[] => /tmp/soap.log,[] => ,[] => ,[] => ,[] => ,[] => 100,[] => 1,[] => Monolog\Formatter\LineFormatter Object ([] => [%datetime%] %channel%.%level_name%: %message% %context% %extra%
,[] => 1,[] => 1,[] => ,[] => Y-m-d H:i:s),[] => Array ())),[] => Array (),[] => 1),[] => Monolog\Logger Object ([] => AW_REPORT_DOWNLOADER,[] => Array ([0] => Monolog\Handler\StreamHandler Object ([] => ,[] => /tmp/report-downloader.log,[] => ,[] => ,[] => ,[] => ,[] => 100,[] => 1,[] => Monolog\Formatter\LineFormatter Object ([] => [%datetime%] %channel%.%level_name%: %message% %context% %extra%
,[] => 1,[] => 1,[] => ,[] => Y-m-d H:i:s),[] => Array ())),[] => Array (),[] => 1),[] => Monolog\Logger Object ([] => AW_BATCH_JOBS_UTIL,[] => Array ([0] => Monolog\Handler\StreamHandler Object ([] => ,[] => /tmp/bjutil.log,[] => ,[] => ,[] => ,[] => ,[] => 100,[] => 1,[] => Monolog\Formatter\LineFormatter Object ([] => [%datetime%] %channel%.%level_name%: %message% %context% %extra%
,[] => 1,[] => 1,[] => ,[] => Y-m-d H:i:s),[] => Array ())),[] => Array (),[] => 1),[] => Google\AdsApi\Common\AdsHeaderFormatter Object ([] => Google\AdsApi\Common\AdsUtilityRegistry Object ([] => Array ()),[] => Google\AdsApi\Common\LibraryMetadataProvider Object ([] => googleads-php-lib,[] => 27.1.0)))) called at [/var/app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:86]
#4  Google\AdsApi\Common\AdsSoapClient->__soapCall(get, Array ([0] => Array ([serviceSelector] => Google\AdsApi\AdWords\v201705\cm\Selector Object ([] => Array ([0] => Id,[1] => Name),[] => ,[] => ,[] => Array ([0] => Google\AdsApi\AdWords\v201705\cm\OrderBy Object ([] => Name,[] => ASCENDING)),[] => Google\AdsApi\AdWords\v201705\cm\Paging Object ([] => 0,[] => 500))))) called at [/var/app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201705/cm/CampaignService.php:157]
#5  Google\AdsApi\AdWords\v201705\cm\CampaignService->get(Google\AdsApi\AdWords\v201705\cm\Selector Object ([] => Array ([0] => Id,[1] => Name),[] => ,[] => ,[] => Array ([0] => Google\AdsApi\AdWords\v201705\cm\OrderBy Object ([] => Name,[] => ASCENDING)),[] => Google\AdsApi\AdWords\v201705\cm\Paging Object ([] => 0,[] => 500))) called at [/var/app/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/GetCampaigns.php:50]
#6  Google\AdsApi\Examples\AdWords\v201705\BasicOperations\GetCampaigns::runExample(Google\AdsApi\AdWords\AdWordsServices Object ([] => Google\AdsApi\Common\AdsSoapClientFactory Object ([] => Google\AdsApi\Common\Util\Reflection Object (),[] => Google\AdsApi\Common\SoapLogMessageFormatter Object ([] => Array ([0] => Authorization),[] => Array ([0] => developerToken),[] => Array ([0] => clientCustomerId),[] => Array ([0] => operations),[] => 16000),[] => 600),[] => Google\AdsApi\AdWords\AdWordsHeaderHandler Object ([] => Google\AdsApi\Common\AdsHeaderFormatter Object ([] => Google\AdsApi\Common\AdsUtilityRegistry Object ([] => Array ()),[] => Google\AdsApi\Common\LibraryMetadataProvider Object ([] => googleads-php-lib,[] => 27.1.0)),[] => Google\AdsApi\Common\Util\Reflection Object (),[] => Google\AdsApi\Common\Util\OAuth2TokenRefresher Object ([] => 60))), Google\AdsApi\AdWords\AdWordsSession Object ([] => token_A,[] => unknown,[] => https://adwords.google.com/,[] => Google\Auth\Credentials\UserRefreshCredentials Object ([] => Google\Auth\OAuth2 Object ([] => ,[] => GuzzleHttp\Psr7\Uri Object ([] => https,[] => ,[] => www.googleapis.com,[] => ,[] => /oauth2/v4/token,[] => ,[] => ),[] => ,[] => part1-part2.apps.googleusercontent.com,[] => other_token-other_token_suffix,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => 3600,[] => ,[] => ,[] => 1/some_token-some_hash,[] => ,[] => ,[] => ,[] => ,[] => ,[] => ,[] => Array ())),[] => Google\AdsApi\Common\SoapSettings Object ([] => 9,[] => 0,[] => some.proxy.domain,[] => 12345,[] => some_proxy_user,[] => some_proxy_pass,[] => 1,[] => ),[] => customer_id,[] => ,[] => ,[] => 1,[] => Google\AdsApi\AdWords\ReportSettings Object ([] => ,[] => ,[] => ,[] => ,[] => ),[] => Monolog\Logger Object ([] => AW_SOAP,[] => Array ([0] => Monolog\Handler\StreamHandler Object ([] => ,[] => /tmp/soap.log,[] => ,[] => ,[] => ,[] => ,[] => 100,[] => 1,[] => Monolog\Formatter\LineFormatter Object ([] => [%datetime%] %channel%.%level_name%: %message% %context% %extra%
,[] => 1,[] => 1,[] => ,[] => Y-m-d H:i:s),[] => Array ())),[] => Array (),[] => 1),[] => Monolog\Logger Object ([] => AW_REPORT_DOWNLOADER,[] => Array ([0] => Monolog\Handler\StreamHandler Object ([] => ,[] => /tmp/report-downloader.log,[] => ,[] => ,[] => ,[] => ,[] => 100,[] => 1,[] => Monolog\Formatter\LineFormatter Object ([] => [%datetime%] %channel%.%level_name%: %message% %context% %extra%
,[] => 1,[] => 1,[] => ,[] => Y-m-d H:i:s),[] => Array ())),[] => Array (),[] => 1),[] => Monolog\Logger Object ([] => AW_BATCH_JOBS_UTIL,[] => Array ([0] => Monolog\Handler\StreamHandler Object ([] => ,[] => /tmp/bjutil.log,[] => ,[] => ,[] => ,[] => ,[] => 100,[] => 1,[] => Monolog\Formatter\LineFormatter Object ([] => [%datetime%] %channel%.%level_name%: %message% %context% %extra%
,[] => 1,[] => 1,[] => ,[] => Y-m-d H:i:s),[] => Array ())),[] => Array (),[] => 1),[] => Google\AdsApi\Common\AdsHeaderFormatter Object ([] => Google\AdsApi\Common\AdsUtilityRegistry Object ([] => Array ()),[] => Google\AdsApi\Common\LibraryMetadataProvider Object ([] => googleads-php-lib,[] => 27.1.0)))) called at [/var/app/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/GetCampaigns.php:84]
#7  Google\AdsApi\Examples\AdWords\v201705\BasicOperations\GetCampaigns::main() called at [/var/app/vendor/googleads/googleads-php-lib/examples/AdWords/v201705/BasicOperations/GetCampaigns.php:88]
```

**Comment by sebastianpiskorski** [comment]
And her is how I inject proxy, [here is injection point](https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php?utf8=%E2%9C%93#L501)

and it looks like this:
```
$response = $httpHandler($this->generateCredentialsRequest(), ['debug' => true,'proxy' => 'http://some_proxy_user:some_proxy_pass@some.proxy.domain:12345']);
```

**Comment by fiboknacky** [comment]
Could you share your `adsapi_php.ini` where you put your proxy info too please?
And what client lib version are you using?

**Comment by sebastianpiskorski** [comment]
```
[PROXY]
; Optional proxy settings to be used by SOAP requests.
host = "some.proxy.domain"
port = 12345
user = "some_proxy_user"
password = "some_proxy_pass"
```

**Comment by fiboknacky** [comment]
What client library version are you using?

**Comment by sebastianpiskorski** [comment]
`v201705`
`"googleads/googleads-php-lib": "^27.0.0"`

**Comment by fiboknacky** [comment]
OK. v27.0.0 doesn't support proxy in the authentication part yet.
Please upgrade to the latest version.

**Comment by sebastianpiskorski** [comment]
😢

**Comment by fiboknacky** [comment]
As FYI, v201705 will be sunset [in two months](https://developers.google.com/adwords/api/docs/sunset-dates).
So, you probably want to prepare upgrading soon. :)

**Comment by sebastianpiskorski** [comment]
I don't know what to say. It took us half a year to determine that lib doesn't support proxy calls for OAuth2. I'm not even mad. xD
