### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by asmagillani** [googleads/googleads-php-lib#400]
I am facing this issue again and again
SoapFault in AdsSoapClient.php line 68:
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/o/v201708/TrafficEstimatorService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/o/v201708/TrafficEstimatorService?wsdl"

i have followed the thread  https://github.com/googleads/googleads-php-lib/issues/353  but invain 

please suggest the solution

Thanks

**Comment by fiboknacky** [comment]
Hello @asmagillani 

Do you face with this issue for all services and reporting? Or does it happen intermittently?
The new version ([v32.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/32.0.0)) now ships local WSDL files, so it doesn't rely on the live WSDLs anymore.

Could you please try this version too?

Best,
Knack

**Comment by tingShean** [comment]
Hello @fiboknacky 

i have the same issue with new version(v32.0.0)

```
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/mcm/v201710/ManagedCustomerService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/mcm/v201710/ManagedCustomerService?wsdl"

Filename: Common/AdsSoapClient.php

Line Number: 75
```

this issue happend a few days (maybe 11/16)

Thanks

**Comment by asmagillani** [comment]
Hello @fiboknacky 
I am having this issue most of the time on local machine it always shown but on server it happened some time i have upgrade with new version as well tell me how i can resolve it

Thanks

**Comment by fiboknacky** [comment]
OK. Please let me know if this persists after you upgrade.

Best,
Knack

**Comment by songxiaoxiao** [comment]
这个问题可以试着curl 访问下 https://adwords.google.com/api/adwords/o/v201708/TrafficEstimatorService?wsdl这个地址。是需要翻墙的。

**Comment by DorianBct** [comment]
Hi,
We've been experiencing the same issue and upon reading this [release note](https://github.com/googleads/googleads-php-lib/releases/tag/32.0.0) we decided to upgrate to 32.0.0 (201710) from a previous release of 201705 but to no avail. We experience this error with atleast BudgetService and AdGroupService.

In the release note it is said that 

> Included WSDL files for all SOAP services and they're now used for making
> SOAP calls instead of live WSDLs. Therefore, the WSDL caching feature is
> deprecated (wsdlCache in adsapi_php.ini is now ignored). The feature
> will be removed completely in the next major release.

Upon diffing our repo we do not find those wsdl files, only a single `campaign-service.wsdl` file in `src/Google/AdsApi/AdWords/Testing`. 

This error is greatly slowing us down from migrating our system to the 201705 (and beyond) to survive the February sunset date, any help would be appreciated. @fiboknacky 

Thanks

**Comment by QuimQuimQuim** [comment]
Hello,

I changed from alder version. Used v32 and adapted to the new auth method using adsapi_php.ini
I tried several exemples from several versions (from 201702 to the last)
have same problem. From time to time it works but usually sends:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201702/AdGroupCriterionService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201702/AdGroupCriterionService?wsdl" in C:\xampp\htdocs\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:75 
Stack trace: 
#0 C:\xampp\htdocs\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php(75): SoapClient->SoapClient('https://adwords...', Array) 
#1 C:\xampp\htdocs\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\v201702\cm\AdGroupCriterionService.php(170): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array) 
#2 [internal function]: Google\AdsApi\AdWords\v201702\cm\AdGroupCriterionService->__construct(Array) 
#3 C:\xampp\htdocs\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\Util\Reflection.php(39): ReflectionClass->newInstanceArgs(Array) 
#4 C:\xampp\htdocs\vendor\google in C:\xampp\htdocs\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 75

it now a week trying, sience ichange from  201609, please help me to search a way to move on

**Comment by songxiaoxiao** [comment]
@QuimQuimQuim   First you have to make sure your network access is unrestricted and then debug at breakpoints.That's how I came

**Comment by TerryScrimsher** [comment]
I have been getting a similar error, and so far no guides I've come across have been able to help with this SOAP-ERROR. Everything seems to be set up correctly on my end, and I am using v32.0.0 from a fresh install just a few hours ago. 

I also have no problems viewing "https://adwords.google.com/api/adwords/cm/v201710/CampaignService?wsdl" in a web browser or by using curl. 

Error Message:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://adwords.google.com/api/adwords/cm/v201710/CampaignService?wsdl' : failed to load external entity "https://adwords.google.com/api/adwords/cm/v201710/CampaignService?wsdl"
 in C:\wamp64\www\development\adwords-examples\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php:75
Stack trace:
#0 C:\wamp64\www\development\adwords-examples\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php(75): SoapClient->SoapClient('https://adwords...', Array)
#1 C:\wamp64\www\development\adwords-examples\vendor\googleads\googleads-php-lib\src\Google\AdsApi\AdWords\v201710\cm\CampaignService.php(146): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array)
#2 [internal function]: Google\AdsApi\AdWords\v201710\cm\CampaignService->__construct(Array)
#3 C:\wamp64\www\development\adwords-examples\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\Util\Reflection.php(3 in C:\wamp64\www\development\adwords-examples\vendor\googleads\googleads-php-lib\src\Google\AdsApi\Common\AdsSoapClient.php on line 75

**Comment by fiboknacky** [comment]
Hello @TerryScrimsher 

Have you tried troubleshooting based on [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues)?

Best,
Knack

**Comment by TerryScrimsher** [comment]
That did the trick! Now I just have to deal with the new error messages I'm getting now.

**Comment by truonggiangdao** [comment]
Thanks @fiboknacky, I had the same issue and tried many thing but didn't works, finally I used disableSslVerify() then it works now.

**Comment by Vijaysinh** [comment]
@truonggiangdao  Could you please share your code line how you have used disableSslVerify() to resolve error?

**Comment by fiboknacky** [comment]
Hi @Vijaysinh 

Below is the code for disableSslVerify():

```php
$oAuth2Credential = (new OAuth2TokenBuilder())
    ->fromFile()
    ->build();
$soapSettings = (new SoapSettingsBuilder())
    ->disableSslVerify()
    ->build();
$session = (new AdWordsSessionBuilder())
    ->fromFile()
    ->withSoapSettings($soapSettings)
    ->withOAuth2Credential($oAuth2Credential)
    ->build();
```

Best,
Knack

**Comment by Vijaysinh** [comment]
Thank you so much @fiboknacky

**Comment by fiboknacky** [comment]
Hello All,

As there are many people jumping into this thread, I may miss to answer some questions, so please speak up if your questions are not answered yet.
(To the best of my knowledge, all are answered either by me or other kind users)
