### ISSUE TITLE
Problem with cronjob 

### ISSUE THREAD

**Issue by giant5X** [googleads/googleads-php-lib#474]
I am using laravel and retrieving data from adwords API the issue is everything's working if I use request the code to be executed through a browser request but when I try to request information using cronjob all hell breaks loose 

`
$ php artisan schedule:run
[32mRunning scheduled command:[39m App\Http\Controllers\ReportController@pullr
eport
[2018-03-27 04:35:50] AW_REPORT_DOWNLOADER.WARNING: clientCustomerId=XXX-XXX-XXXX unknown (AwApi-PHP, googleads-php-lib/31.0.0, PHP/7.1.11, GuzzleHttp/6.2.1, cu
rl/7.56.0) "POST /api/adwords/reportdownload/v201710 HTTP/1.1" Status: NULL
[2018-03-27 04:35:50] AW_REPORT_DOWNLOADER.NOTICE: Request:
POST /api/adwords/reportdownload/v201710 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: adwords.google.com
Authorization: REDACTED
developerToken: REDACTED
clientCustomerId: 273-548-8513
User-Agent: unknown (AwApi-PHP, googleads-php-lib/31.0.0, PHP/7.1.11, GuzzleHttp
/6.2.1, curl/7.56.0)
skipReportHeader: false
skipColumnHeader: false
skipReportSummary: false
useRawEnumValues: false

__rdquery=SELECT CreativeFinalUrls,Path1,Path2,HeadlinePart1,HeadlinePart2,Impre
ssions,Clicks,Conversions,Ctr,Cost,CampaignName,AdGroupName FROM AD_PERFORMANCE_
REPORT WHERE Ctr > 0 DURING 20180201,20180228&__fmt=XML

Response:
REDACTED REPORT DATA
--------
Error:
Error creating resource: [message] fopen(): SSL operation failed with code 1. Op
enSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify faile
d
[file] D:\wamp64\www\bbkapi\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.p
hp
[line] 324
[message] fopen(): Failed to enable crypto
[file] D:\wamp64\www\bbkapi\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.p
hp
[line] 324
[message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201710):
failed to open stream: operation failed
[file] D:\wamp64\www\bbkapi\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.p
hp
[line] 324

`

**Comment by fiboknacky** [comment]
Are there any parts in the cron job that have different SSL certificate settings?
Could you please follow [this wiki](https://github.com/googleads/googleads-php-lib/wiki/Steps-for-troubleshooting-CA-file-issues) to troubleshoot?

Best,
Knack

**Comment by scamexdotexe** [comment]
Hello @fiboknacky

I am having the same issue. The script works if I try to run through the browser but not if it is executed through crontab. I am not sure how to troubleshoot now.

**Comment by fiboknacky** [comment]
What are the errors you see when you run in the crontab?
Are there any parts in the cron job that have different SSL certificate settings?

**Comment by scamexdotexe** [comment]
This is what I'm seeing in error.log:

AW_REPORT_DOWNLOADER.INFO: clientCustomerId=5**-408-0097 unknown (AwApi-PHP, googleads-php-lib/40.0.0, PHP/7.2.19-0ubuntu0.18.04.2, GuzzleHttp/6.3.3, curl/7.58.0) "POST /api/adwords/reportdownload/v201809 HTTP/1.1"

**Comment by fiboknacky** [comment]
Hmm.. That doesn't look like an error. The log is also printed at the INFO level too.
What kind of requests have you sent?
And are all environments (PHP versions, Guzzle versions, OS) the same as when you use the library outside the crontab?

**Comment by scamexdotexe** [comment]
I'm trying to get click performance data.

```
   $reportQuery = 'SELECT ' . $columns
                   . ' FROM CLICK_PERFORMANCE_REPORT '
                   . ' DURING YESTERDAY';
```

`InvalidArgumentException: C           onfig file not found as specified: 'adsapi_php.ini' or in the home directory: '\/home\/ubuntu\/adsapi_php.ini'. in \/           var\/www\/html\/dash\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/Common\/ConfigurationLoader.php:67\n           Stack trace:\n#0 \/var\/www\/html\/dash\/vendor\/googleads\/googleads-php-lib\/src\/Google\/AdsApi\/AdWords\/AdWordsS           essionBuilder.php(110): Google\\AdsApi\\Common\\ConfigurationLoader->fromFile('adsapi_php.ini')\n#1 \/var\/www\/html\           /dash\/clickreportdownloader.php(63): Google\\AdsApi\\AdWords\\AdWordsSessionBuilder->fromFile()\n#2 {main}"}ubuntu@s `

I'd assume that the versions and others are the same but it throws this exception when trying to execute in command line instead of through the browser.

**Comment by scamexdotexe** [comment]
hmm seems like I have to copy .ini file into the home directory,.

**Comment by fiboknacky** [comment]
Probably yes. The message is obvious that the file is not there. Please ensure that the file is ready for use. :)
