### ISSUE TITLE
Fatal error when downloading KEYWORDS_PERFORMANCE_REPORT

### ISSUE THREAD

**Issue by ryutaro-brainlabs** [googleads/googleads-php-lib#479]
I am trying to download all keywords in an account with about 3 million keywords.
When I run this,
```
<?php
require __DIR__ . '/../vendor/autoload.php';

use Google\AdsApi\AdWords\Reporting\v201802\ReportDownloader;
use Google\AdsApi\AdWords\v201802\cm\ApiException;
use Google\AdsApi\AdWords\v201802\cm\RateExceededError;
use Google\AdsApi\AdWords\v201802\cm\DatabaseError;
use Google\AdsApi\AdWords\v201802\cm\DatabaseErrorReason;
use Google\AdsApi\AdWords\v201802\cm\InternalApiError;
use Google\AdsApi\AdWords\AdWordsSession;
use Google\AdsApi\AdWords\AdWordsSessionBuilder;
use Google\AdsApi\AdWords\ReportSettingsBuilder;
use Google\AdsApi\Common\OAuth2TokenBuilder;
use Google\AdsApi\Common\SoapSettingsBuilder;

$clientId = '';
$clientSecret = '';
$refreshToken = '';
$customerId = '';
$developerToken = '';

$session = (new AdWordsSessionBuilder())
->withOAuth2Credential((new OAuth2TokenBuilder())
->withClientId($clientId)
->withClientSecret($clientSecret)
->withRefreshToken($refreshToken)
->build()
)
->withClientCustomerId($customerId)
->withDeveloperToken($developerToken)
->build();

$downloader = new ReportDownloader($session);

$query = 'SELECT AdGroupId, AdGroupName, Id FROM KEYWORDS_PERFORMANCE_REPORT '
$dst = __DIR__ . '/report.csv';

$result = $downloader->downloadReportWithAwql($query, 'CSV');
echo 'saving file' . PHP_EOL;
$result->saveToFile($dst);
```

I consistently get this

```
[2018-04-16 14:23:54] AW_REPORT_DOWNLOADER.WARNING: clientCustomerId=8467812787 unknown (AwApi-PHP, googleads-php-lib/33.1.0, PHP/7.0.24, GuzzleHttp/6.2.1, curl/7.43.0) "POST /api/adwords/reportdownload/v201802 HTTP/1.1" Status: NULL   
[2018-04-16 14:23:54] AW_REPORT_DOWNLOADER.NOTICE: Request:
POST /api/adwords/reportdownload/v201802 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Host: adwords.google.com
Authorization: REDACTED
developerToken: REDACTED
clientCustomerId: REDACTED
User-Agent: unknown (AwApi-PHP, googleads-php-lib/33.1.0, PHP/7.0.24, GuzzleHttp/6.2.1, curl/7.43.0)
skipReportHeader: false
skipColumnHeader: false
skipReportSummary: false
useRawEnumValues: false

__rdquery=SELECT AdGroupId, AdGroupName, Id FROM KEYWORDS_PERFORMANCE_REPORT &__fmt=CSV

Response:
REDACTED REPORT DATA
--------
Error:
Error creating resource: [message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201802): failed to open stream: HTTP request failed! 
[file] /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324
  
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201802): failed to open stream: HTTP request failed! 
[file] /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(52): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy:: in /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52

Fatal error: Uncaught RuntimeException: Error creating resource: [message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201802): failed to open stream: HTTP request failed! 
[file] /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:252
Stack trace:
#0 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(52): GuzzleHttp\Handler\StreamHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#3 /Users/ryutaro/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy:: in /Users/ryutaro/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 52
```

**Comment by fiboknacky** [comment]
Hello,

Can you try sending a smaller request to see if it works?
For example, using a date range, like `DURING 20180401,20180407` would help mitigate this issue.

Best,
Knack

**Comment by ryutaro-brainlabs** [comment]
`DURING YESTERDAY` failed with the same error. It will work if I limit it to e.g. certain campaigns. But we want to get all keywords (and its ad group ID) in the account. The work-around we're thinking of is getting all campaign IDs, partitioning them, then doing multiple queries, filtering on campaign IDs. This fails if one campaign has lots of keywords, so we want to avoid this if possible.

**Comment by fiboknacky** [comment]
I'm afraid that getting all 3M keywords is too large that the library can work on.
You would need to do further partitioning based on your ad group IDs too.

**Comment by ryutaro-brainlabs** [comment]
Ok thanks. Do you know if this is a limitation of the AdWords API or the client library / guzzle?

**Comment by fiboknacky** [comment]
I think it's a combination of both PHP and the libraries.
You may try doing this on other client libraries (e.g., Java) too. :)

**Comment by ryutaro-brainlabs** [comment]
Brilliant, thanks!
