### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in ......./googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:78

### ISSUE THREAD

**Issue by astrotauter** [googleads/googleads-php-lib#502]
Hi !

I posted this issue on Adwords API forum, but Adwords API Team suggested to post this issue on PHP client library. You can see my problem in below link

https://groups.google.com/forum/#!topic/adwords-api/9JlXrmkMuNE
-------------------------------------------------------------------------------
I googled a lot about this error, but all is saying network or ISP problems.
I set Adwords account automatically with API, but this error occurs from time to time. And the locations in which error happens are different.
Even though I moved to another places for setting the same error happens. 
What should I do to escape from this problem?

When I have tested in another adwords account, this kind of error doesn't happen.
Is it possible that specific Adwords server has a network problem?
-------------------------------------------------------------------------------

Thanks  in advance!

**Comment by fiboknacky** [comment]
Hello there,

Could you first describe how you installed this library?
And did you also get [WSDLs](https://github.com/googleads/googleads-php-lib/tree/master/resources/wsdls) installed locally too?

> When I have tested in another adwords account, this kind of error doesn't happen.
Could you tell what kinds of account it is? Is it the [test account](https://developers.google.com/adwords/api/docs/guides/accounts-overview#test_accounts) or production account?
If you could tell the IDs of both accounts, it would be great.

Regards,
Knack

**Comment by astrotauter** [comment]
Hi,

After I posted this, I fortunately succeeded in Adwords setting with API on the right account I wish to set. But I am afraid this kind of errors would happen again.

I installed adwords-php-library with wget command, and the account that I tested was another product account. The account that made problems is 'astrotauter08@gmail.com' and '위너투자-주식1' campaign.

Thanks ^^

**Comment by fiboknacky** [comment]
> I installed adwords-php-library with wget command, and the account that I tested was another product account. The account that made problems is 'astrotauter08@gmail.com' and '위너투자-주식1' campaign.

That doesn't sound like a typical way of installing the library.
Have you followed any of the steps described in [README](https://github.com/googleads/googleads-php-lib#downloading-this-library)?

And could you answer all my questions in the previous reply?
* Did you also get WSDLs installed locally too?
* Could you tell what kinds of account it is?
* Is it the test account or production account?

Best,
Knack

**Comment by astrotauter** [comment]
Hi,

I'm sorry for my bad memory. I remember I installed this library 'using composer require', and I am using this library on web browser. My account is product account.

Below is the error log.

Thanks!

---------------------------------------------------------------------------------------------------------
Fatal error: Uncaught SoapFault exception: [HTTP] Could not connect to host in /var/www/html/ad_manager/google_v201710/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:78
Stack trace:
#0 /var/www/html/ad_manager/google_v201710/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(78): SoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0)
#1 [internal function]: Google\AdsApi\Common\AdsSoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0)
#2 /var/www/html/ad_manager/google_v201710/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(119): SoapClient->__soapCall('mutate', Array, NULL, Array, Array)
#3 /var/www/html/ad_manager/google_v201710/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201710/cm/AdGroupAdService.php(191): Google\AdsApi\Common\AdsSoapClient->__soapCall('mutate', Array)
#4 /var/www/html/ad_manager/google_v201710/googleads/googleads-php-lib/examples/AdWords/v201710/BasicOperations/AddExpandedTextAd in /var/www/html/ad_manager/google_v201710/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 78
---------------------------------------------------------------------------------------------------------

**Comment by fiboknacky** [comment]
Could you update to v201806 please, as [v201710 is going to be sunset](https://developers.google.com/adwords/api/docs/sunset-dates) very soon?
This might be a cause of the errors as well.

Finally, you haven't answered my question regarding WSDLs yet.
> Did you also get WSDLs installed locally too?

**Comment by astrotauter** [comment]
I'm sorry but I don't remember how I installed WSDL. 

Anyway I had better update to the latest version. 

Thanks!
