### ISSUE TITLE
Error: Call to a member function withBody() on null

### ISSUE THREAD

**Issue by ShintaroNitta** [googleads/googleads-php-lib#568]
I'm using `v201809`.

I think there is a possibility to occur the following `Error` inside `Callable` which is generated from `Google\AdsApi\Common\GuzzleLogMessageHandler::log()` .
I have encountered this issue in my system from Feb 5th 2019, I think it happens when connection timeout or something.

```
Error: Call to a member function withBody() on null
2019-02-06 09:36:45 Error: Call to a member function withBody() on null
#0 /var/www/html/listing/vendor/guzzlehttp/promises/src/RejectedPromise.php(40): Google\AdsApi\Common\GuzzleLogMessageHandler::Google\AdsApi\Common\{closure}(Object(GuzzleHttp\Exception\RequestException))
#1 /var/www/html/listing/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
#2 /var/www/html/listing/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#3 /var/www/html/listing/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#4 /var/www/html/listing/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#5 /var/www/html/listing/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Promise\Promise->wait()
#6 /var/www/html/listing/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201809/ReportDownloader.php(214): GuzzleHttp\Client->request('POST', 'https://adwords...', Array)
#7 /var/www/html/listing/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/Reporting/v201809/ReportDownloader.php(122): Google\AdsApi\AdWords\Reporting\v201809\ReportDownloader->makeReportRequest(Array)
#8 /var/www/html/listing/src/Shell/Media/AdWords/Report/AccountAreaReport.php(96): Google\AdsApi\AdWords\Reporting\v201809\ReportDownloader->downloadReport(Object(Google\AdsApi\AdWords\Reporting\v201809\ReportDefinition))
#9 /var/www/html/listing/src/Shell/Media/AdWords/Report/AccountAreaReport.php(64): App\Shell\Media\AdWords\Report\AccountAreaReport->downloadReport()
```

**Comment by fiboknacky** [comment]
Hello,

Thanks for reporting. Will work on this.

**Comment by chiragvels** [comment]
Hi @fiboknacky ,
I have started facing this issue.
`Call to a member function withBody() on null in /googleads/googleads-php-lib/src/Google/AdsApi/Common/GuzzleLogMessageHandler.php on line 93`

Thanks,

**Comment by chiragvels** [comment]
@ShintaroNitta , You are still facing issue, If not what could I need to change to resolve issue?

**Comment by fiboknacky** [comment]
Hi Chirag,

Can you add an if clause around lines 93 - 95:

```
if (!is_null($response) && !is_null($response->getBody())) {
  $cachedResponse = $response->withBody(
      new CachingStream($response->getBody())
  );
}
```

I'll push the fix soon in the next release.

Best,
Knack

**Comment by chiragvels** [comment]
Hi @fiboknacky ,

Yes, I have added.
Let me see reporting today.

Thanks,

**Comment by fiboknacky** [comment]
[v40.0.0](https://github.com/googleads/googleads-php-lib/releases/tag/40.0.0) should fix this issue.
Could you please upgrade and try again?

**Comment by chiragvels** [comment]
hi,
through composer it is still saying I am on latest version.
Nothing to install or update

Thanks,

**Comment by fiboknacky** [comment]
Could you try again?

**Comment by chiragvels** [comment]
Yes, working now.

Thanks,
