### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [HTTP] unknown

### ISSUE THREAD

**Issue by hybmg57** [googleads/googleads-php-lib#586]
I'm getting below errors all of a sudden today. Do you know what is wrong?

`Fatal error: Uncaught SoapFault exception: [HTTP] unknown in /var/www/vhosts/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:97 Stack trace: #0 /var/www/vhosts/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(97): SoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0) #1 [internal function]: Google\AdsApi\Common\AdsSoapClient->__doRequest('<?xml version="...', 'https://adwords...', '', 1, 0) #2 /var/www/vhosts/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(152): SoapClient->__soapCall('get', Array, NULL, Array, Array) #3 /var/www/vhosts/googleads-php-lib/src/Google/AdsApi/AdWords/v201809/o/TargetingIdeaService.php(152): Google\AdsApi\Common\AdsSoapClient->__soapCall('get', Array) #4 /var/www/vhosts/keyword_api.php(134): Google\AdsApi\A in /var/www/vhosts/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php on line 97`

**Comment by hybmg57** [comment]
After doing "git pull origin master" and running "ini_set("soap.wsdl_cache_enabled", 0);" it works now. It seem to have generated another wsdl cache file under tmp folder. Was anything changed in wsdl?

**Comment by fiboknacky** [comment]
As far as I know, we haven't changed anything in the WSDL files recently.

**Comment by fiboknacky** [comment]
I'm closing this as there are no activity right now. Feel free to re-open this if you still face with the issue.
