### ISSUE TITLE
ExtensionSettingError.MISSING_FIELD ... sitelinkLine3

### ISSUE THREAD

**Issue by dragon658** [googleads/googleads-php-lib#606]
This is my code:

 ```
$sitelinks = [];
    foreach ($dop as $d) {
      $sitelink1 = new SitelinkFeedItem();
      $sitelink1->setSitelinkText($d['Title']);
      $sitelink1->setSitelinkLine2($d['Description']);
      $sitelink1->setSitelinkLine3('');
      $sitelink1->setSitelinkFinalUrls(
        new UrlList([$d['Href'].'&utm_source=google&utm_medium=cpc&utm_campaign='.$utm])
      );
      $sitelinks[] = $sitelink1;
    }
    $campaignExtensionSetting = new CampaignExtensionSetting();
    $campaignExtensionSetting->setCampaignId($campaign_id);
    $campaignExtensionSetting->setExtensionType(FeedType::SITELINK);
    $campaignExtensionSetting->setExtensionSetting(new ExtensionSetting());
    $campaignExtensionSetting->getExtensionSetting()->setExtensions($sitelinks);
    $operation = new CampaignExtensionSettingOperation();
    $operation->setOperator(Operator::ADD);
    $operation->setOperand($campaignExtensionSetting);
    $operations = [$operation];
    $campaignExtensionSettingService->mutate($operations);
```

When I execute it, I get this error:

> 2019/07/22 17:42:24 [error] 614#614: *2061756 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Google\AdsApi\AdWords\v201809\cm\ApiException: [ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[0].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[1].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[2].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[3].sitelinkLine3] in ..../vendor/googleads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php:43
> Stack trace:
> #0 ..../vendor/googleads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(43): ReflectionClass->newInstanceArgs(Array)
> #1 ..../vendor/googleads/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(202): Google\AdsApi\Common\Util\" while reading response header from upstream

This error says that I didnt specify SitelinkLine3. But I specified it in the code.
When I changed line 
$sitelink1->setSitelinkLine3('');
to
$sitelink1->setSitelinkLine3('123');
the error disappeared!
But line3 is not required for google ads. I want it to be empty.

**Comment by fiboknacky** [comment]
If you don't specify anything about siteLinkLine3 at all, would the error disappear?

**Comment by dragon658** [comment]
If I delete line
$sitelink1->setSitelinkLine3('');
error still remains.
When I cought this error 1 time there were no this line at all.

**Comment by fiboknacky** [comment]
Could you please share your request ID as well? I need to look up full SOAP logs for better investigation.
Thank you.

**Comment by dragon658** [comment]
How to get request ID? I just use code like this and dont know in depth how to work with this lib.

```
$adWordsServices = new AdWordsServices();
    $session = $this->getSession();
    $budgetService = $adWordsServices->get($session, BudgetService::class);
    $campaignService = $adWordsServices->get($session, CampaignService::class);
...
$operation->setOperand($campaignExtensionSetting);
    $operations = [$operation];
    $campaignExtensionSettingService->mutate($operations);
```

**Comment by fiboknacky** [comment]
The request ID will be in your SOAP response if you turn on [logging](https://github.com/googleads/googleads-php-lib#logging). 
Could you turn on logging and get the request ID first?

**Comment by dragon658** [comment]
My request ID is 00058e57bdd079470a37db0a3407b9d1

**Comment by fiboknacky** [comment]
I cannot find your log on the server. 
Could you show your SOAP request and response here (and also hide all sensitive information) please?

**Comment by dragon658** [comment]
Here is it. By the way, I do this on my test account.

```
[2019-07-23 14:46:21] AW_SOAP.WARNING: clientCustomerId=************ operations=5 service=CampaignExtensionSettingService method=mutate responseTime=143 requestId=00058e57bdd079470a37db0a3407b9d1 server=adwords.google.com isFault=1 faultMessage=[ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[0].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[1].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[2].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[3].sitelinkLine3]  
[2019-07-23 14:46:21] AW_SOAP.NOTICE: POST /api/adwords/cm/v201809/CampaignExtensionSettingService?wsdl HTTP/1.1
Host: adwords.google.com
Connection: close
User-Agent: PHP-SOAP/7.0.32-0ubuntu0.16.04.1
Content-Type: text/xml; charset=utf-8
SOAPAction: ""
Content-Length: 2748
Authorization: REDACTED

<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://adwords.google.com/api/adwords/cm/v201809" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><SOAP-ENV:Header><ns1:RequestHeader><ns1:clientCustomerId>************</ns1:clientCustomerId><ns1:developerToken>REDACTED</ns1:developerToken><ns1:userAgent>unknown (AwApi-PHP, googleads-php-lib/38.0.0, PHP/7.0.32-0ubuntu0.16.04.1)</ns1:userAgent><ns1:validateOnly>false</ns1:validateOnly><ns1:partialFailure>false</ns1:partialFailure></ns1:RequestHeader></SOAP-ENV:Header><SOAP-ENV:Body><ns1:mutate><ns1:operations><ns1:operator>ADD</ns1:operator><ns1:operand><ns1:campaignId>******</ns1:campaignId><ns1:extensionType>SITELINK</ns1:extensionType><ns1:extensionSetting><ns1:extensions xsi:type="ns1:SitelinkFeedItem"><ns1:sitelinkText>123</ns1:sitelinkText><ns1:sitelinkLine2>123</ns1:sitelinkLine2><ns1:sitelinkLine3/><ns1:sitelinkFinalUrls><ns1:urls>***</ns1:urls></ns1:sitelinkFinalUrls></ns1:extensions><ns1:extensions xsi:type="ns1:SitelinkFeedItem"><ns1:sitelinkText>***</ns1:sitelinkText><ns1:sitelinkLine2>***</ns1:sitelinkLine2><ns1:sitelinkLine3/><ns1:sitelinkFinalUrls><ns1:urls>****</ns1:urls></ns1:sitelinkFinalUrls></ns1:extensions><ns1:extensions xsi:type="ns1:SitelinkFeedItem"><ns1:sitelinkText>***</ns1:sitelinkText><ns1:sitelinkLine2>Р***</ns1:sitelinkLine2><ns1:sitelinkLine3/><ns1:sitelinkFinalUrls><ns1:urls>***</ns1:urls></ns1:sitelinkFinalUrls></ns1:extensions><ns1:extensions xsi:type="ns1:SitelinkFeedItem"><ns1:sitelinkText>Гавайские рубашки</ns1:sitelinkText><ns1:sitelinkLine2>С***</ns1:sitelinkLine2><ns1:sitelinkLine3/><ns1:sitelinkFinalUrls><ns1:urls>***</ns1:urls></ns1:sitelinkFinalUrls></ns1:extensions></ns1:extensionSetting></ns1:operand></ns1:operations></ns1:mutate></SOAP-ENV:Body></SOAP-ENV:Envelope>

HTTP/1.1 500 Internal Server Error
Content-Type: text/xml; charset=UTF-8
Date: Tue, 23 Jul 2019 11:46:21 GMT
Expires: Tue, 23 Jul 2019 11:46:21 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Alt-Svc: quic=":443"; ma=2592000; v="46,43,39"
Accept-Ranges: none
Vary: Accept-Encoding
Connection: close

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><ResponseHeader xmlns="https://adwords.google.com/api/adwords/cm/v201809"><requestId>00058e57bdd079470a37db0a3407b9d1</requestId><serviceName>CampaignExtensionSettingService</serviceName><methodName>mutate</methodName><operations>5</operations><responseTime>143</responseTime></ResponseHeader></soap:Header><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>[ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[0].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[1].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[2].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[3].sitelinkLine3]</faultstring><detail><ApiExceptionFault xmlns="https://adwords.google.com/api/adwords/cm/v201809"><message>[ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[0].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[1].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[2].sitelinkLine3, ExtensionSettingError.MISSING_FIELD @ operations[0].operand.extensionSetting.extensions[3].sitelinkLine3]</message><ApplicationException.Type>ApiException</ApplicationException.Type><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ExtensionSettingError"><fieldPath>operations[0].operand.extensionSetting.extensions[0].sitelinkLine3</fieldPath><fieldPathElements><field>operations</field><index>0</index></fieldPathElements><fieldPathElements><field>operand</field></fieldPathElements><fieldPathElements><field>extensionSetting</field></fieldPathElements><fieldPathElements><field>extensions</field><index>0</index></fieldPathElements><fieldPathElements><field>sitelinkLine3</field></fieldPathElements><trigger></trigger><errorString>ExtensionSettingError.MISSING_FIELD</errorString><ApiError.Type>ExtensionSettingError</ApiError.Type><reason>MISSING_FIELD</reason></errors><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ExtensionSettingError"><fieldPath>operations[0].operand.extensionSetting.extensions[1].sitelinkLine3</fieldPath><fieldPathElements><field>operations</field><index>0</index></fieldPathElements><fieldPathElements><field>operand</field></fieldPathElements><fieldPathElements><field>extensionSetting</field></fieldPathElements><fieldPathElements><field>extensions</field><index>1</index></fieldPathElements><fieldPathElements><field>sitelinkLine3</field></fieldPathElements><trigger></trigger><errorString>ExtensionSettingError.MISSING_FIELD</errorString><ApiError.Type>ExtensionSettingError</ApiError.Type><reason>MISSING_FIELD</reason></errors><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ExtensionSettingError"><fieldPath>operations[0].operand.extensionSetting.extensions[2].sitelinkLine3</fieldPath><fieldPathElements><field>operations</field><index>0</index></fieldPathElements><fieldPathElements><field>operand</field></fieldPathElements><fieldPathElements><field>extensionSetting</field></fieldPathElements><fieldPathElements><field>extensions</field><index>2</index></fieldPathElements><fieldPathElements><field>sitelinkLine3</field></fieldPathElements><trigger></trigger><errorString>ExtensionSettingError.MISSING_FIELD</errorString><ApiError.Type>ExtensionSettingError</ApiError.Type><reason>MISSING_FIELD</reason></errors><errors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ExtensionSettingError"><fieldPath>operations[0].operand.extensionSetting.extensions[3].sitelinkLine3</fieldPath><fieldPathElements><field>operations</field><index>0</index></fieldPathElements><fieldPathElements><field>operand</field></fieldPathElements><fieldPathElements><field>extensionSetting</field></fieldPathElements><fieldPathElements><field>extensions</field><index>3</index></fieldPathElements><fieldPathElements><field>sitelinkLine3</field></fieldPathElements><trigger></trigger><errorString>ExtensionSettingError.MISSING_FIELD</errorString><ApiError.Type>ExtensionSettingError</ApiError.Type><reason>MISSING_FIELD</reason></errors></ApiExceptionFault></detail></soap:Fault></soap:Body></soap:Envelope>
```

**Comment by fiboknacky** [comment]
I double-checked my code and when I don't specify anything at all about sitelink3, it works fine because the SOAP toolkit will just not serialize it as an XML.
Could you share your updated code here as well?
Based on the SOAP log you shared, it looks more like sitelink3 is still specified as an empty string.

**Comment by dragon658** [comment]
I completely deleted line 
$sitelink1->setSitelinkLine3('');
and still get the error. :(
requestId=00058e6c05149ec20a37be85800d36c4

This is log file without censorship: (I will delete it after some time)
https://yadi.sk/d/GotOG-4Z0JP1Cw

**Comment by dragon658** [comment]
This is my addDop function:

```
function addDop($campaignExtensionSettingService, $campaign_id, $dop, $utm) { // "расширения", 25 title, 35 desc1, еще не используется desc2
    $sitelinks = [];
    foreach ($dop as $d) {
      $sitelink1 = new SitelinkFeedItem();
      $sitelink1->setSitelinkText($d['Title']);
      $sitelink1->setSitelinkLine2($d['Description']);
//      $sitelink1->setSitelinkLine3(''); // если не указать ошибка
//      $sitelink1->setSitelinkLine3($d['Description']); // если не указать ошибка
      $sitelink1->setSitelinkFinalUrls(
        new UrlList([$d['Href'].'&utm_source=google&utm_medium=cpc&utm_campaign='.$utm])
      );
      $sitelinks[] = $sitelink1;
    }
    $campaignExtensionSetting = new CampaignExtensionSetting();
    $campaignExtensionSetting->setCampaignId($campaign_id);
    $campaignExtensionSetting->setExtensionType(FeedType::SITELINK);
    $campaignExtensionSetting->setExtensionSetting(new ExtensionSetting());
    $campaignExtensionSetting->getExtensionSetting()->setExtensions($sitelinks);
    $operation = new CampaignExtensionSettingOperation();
    $operation->setOperator(Operator::ADD);
    $operation->setOperand($campaignExtensionSetting);
    $operations = [$operation];
    $campaignExtensionSettingService->mutate($operations);
  }
```

**Comment by dragon658** [comment]
```
function createCampaign($name, $minus, $dop, $project_id) {
    $data_keys = ['msk' => '', 'spb' => '', 'region' => ''];
    .....
    $adWordsServices = new AdWordsServices();
    $session = $this->getSession();
    $budgetService = $adWordsServices->get($session, BudgetService::class);
    $campaignService = $adWordsServices->get($session, CampaignService::class);
    $campaignCriterionService = $adWordsServices->get($session, CampaignCriterionService::class);
    **$campaignExtensionSettingService = $adWordsServices->get($session, CampaignExtensionSettingService::class);**
    foreach ($data_keys as $region => $v1) {
      if (!empty($data_keys[$region])) continue;
      $campaign_name = $name.'_'.$region;
      $budget = new Budget();
      $budget->setName($campaign_name);
      $money = new Money();
      $money->setMicroAmount(1000000000);
      $budget->setAmount($money);
      $budget->setDeliveryMethod(BudgetBudgetDeliveryMethod::STANDARD);
      $operations = [];
      $operation = new BudgetOperation();
      $operation->setOperand($budget);
      $operation->setOperator(Operator::ADD);
      $operations[] = $operation;
      $result = $budgetService->mutate($operations);
      $budget = $result->getValue()[0];
      $operations = [];
      $campaign = new Campaign();
      $campaign->setName($campaign_name);
      $campaign->setAdvertisingChannelType(AdvertisingChannelType::SEARCH);
      $campaign->setBudget(new Budget());
      $campaign->getBudget()->setBudgetId($budget->getBudgetId());
      $biddingStrategyConfiguration = new BiddingStrategyConfiguration();
      $biddingStrategyConfiguration->setBiddingStrategyType(
        BiddingStrategyType::MANUAL_CPC
      );
      $biddingScheme = new ManualCpcBiddingScheme();
      $biddingStrategyConfiguration->setBiddingScheme($biddingScheme);
      $campaign->setBiddingStrategyConfiguration($biddingStrategyConfiguration);
      $networkSetting = new NetworkSetting();
      $networkSetting->setTargetGoogleSearch(true);
      $networkSetting->setTargetSearchNetwork(false);
      $networkSetting->setTargetContentNetwork(false);
      $campaign->setNetworkSetting($networkSetting);
      $campaign->setStatus(CampaignStatus::PAUSED);
      $operation = new CampaignOperation();
      $operation->setOperand($campaign);
      $operation->setOperator(Operator::ADD);
      $operations[] = $operation;
      $result = $campaignService->mutate($operations);
      foreach ($result->getValue() as $campaign) {
        $data_keys[$region] = $campaign->getId();
        $this->db->query("INSERT INTO oc_dtec_section_ads_remote SET service='g',region='".$this->db->escape($region)."',ads_version_id=".(int)$project_id.",campaign_id='".(int)$campaign->getId()."',type='campaign'");
        $this->addRegions($region, $campaign->getId(), $adWordsServices, $session);
        $this->addMinus($campaignCriterionService, $campaign->getId(), $minus);
        **$this->addDop($campaignExtensionSettingService, $campaign->getId(), $dop, $name.'_'.$region);**
        break;
      }
    }
    return $data_keys;
  }
```

**Comment by dragon658** [comment]
soapLogLevel = "NOTICE"

**Comment by fiboknacky** [comment]
Your latest SOAP provides enough information for me to escalate to the API engineers. That's really something strange.
I'll keep you updated once I hear more from them.

**Comment by dragon658** [comment]
Ok, thank you.

**Comment by dragon658** [comment]
I just found that I cannot dont fill SitelinkLine3 in AdWords interface!
When I fill line 2 and dont fill line 3, system says "Add both lines". O_O
Maybe this is because I cannot leave line 3 blank with API.
