### ISSUE TITLE
Many `500 Internal Server Error` Recently

### ISSUE THREAD

**Issue by nhtahoe** [googleads/googleads-php-lib#616]
In the last 2 days using v201809/cm/CampaignService.php, I am getting a ton of `Server error: 'POST https://oauth2.googleapis.com/token' resulted in a '500 Internal Server Error'`. I haven't changed anything and everything was working fine before.

Something going on with the service? Here is stack trace:
```
[2019-10-04 06:06:08] production.ERROR: Server error: `POST https://oauth2.googleapis.com/token` resulted in a `500 Internal Server Error` response:
{
  "error": "internal_failure"
}
 {"exception":"[object] (GuzzleHttp\\Exception\\ServerException(code: 500): Server error: `POST https://oauth2.googleapis.com/token` resulted in a `500 Internal Server Error` response:
{
  \"error\": \"internal_failure\"
}
 at app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 app/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 app/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 app/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 app/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 app/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 app/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 app/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 app/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 app/vendor/guzzlehttp/guzzle/src/Client.php(106): GuzzleHttp\\Promise\\Promise->wait()
#10 app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsGuzzleProxyHttpHandler.php(63): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 app/vendor/google/auth/src/OAuth2.php(502): Google\\AdsApi\\Common\\AdsGuzzleProxyHttpHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request))
#12 app/vendor/google/auth/src/Credentials/UserRefreshCredentials.php(119): Google\\Auth\\OAuth2->fetchAuthToken(Object(Google\\AdsApi\\Common\\AdsGuzzleProxyHttpHandler))
#13 app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/OAuth2TokenRefresher.php(66): Google\\Auth\\Credentials\\UserRefreshCredentials->fetchAuthToken(Object(Google\\AdsApi\\Common\\AdsGuzzleProxyHttpHandler))
#14 app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsHeaderHandler.php(70): Google\\AdsApi\\Common\\Util\\OAuth2TokenRefresher->getOrFetchAccessToken(Object(Google\\Auth\\Credentials\\UserRefreshCredentials), Object(Google\\AdsApi\\Common\\AdsGuzzleProxyHttpHandler))
#15 app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(114): Google\\AdsApi\\AdWords\\AdWordsHeaderHandler->generateHttpHeaders(Object(Google\\AdsApi\\AdWords\\AdWordsSession))
#16 app/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201809/cm/CampaignService.php(217): Google\\AdsApi\\Common\\AdsSoapClient->__soapCall('query', Array)
```

**Comment by fiboknacky** [comment]
For seemingly server-related issues, could you please post on the [Google Ads API forum](https://groups.google.com/forum/?nomobile=true#!forum/adwords-api) instead?
Thank you.

**Comment by nhtahoe** [comment]
Hope that works - my experience there has been that they see "php" anywhere in the post and try to send me back here.

**Comment by fiboknacky** [comment]
I'm sorry that you've faced not quite good experience.
For the case like this, there is nothing much we can do on the library side, so it should definitely be handled and escalated in that forum.
Please let me know if you're kept pushed back here.
