### ISSUE TITLE
"Error: A Developer Token Must Be Set" but adsapi_php.ini has been set up

### ISSUE THREAD

**Issue by spaldingl** [googleads/googleads-php-lib#635]
I downloaded the [php library compressed tarball](https://github.com/googleads/googleads-php-lib/blob/master/README.md#downloading-a-compressed-tarball) and followed the instructions after.  Now, when I try and run an example using` php AdsUpdater/adwords-examples-44.0.0/examples/AdWords/v201809/BasicOperations/GetCampaigns.php` I get this error: 
```
PHP Fatal error:  Uncaught InvalidArgumentException: A developer token must be set. in /home/ubuntu/AdsUpdater/adwords-examples-44.0.0/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php:463
Stack trace:
#0 /home/ubuntu/AdsUpdater/adwords-examples-44.0.0/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php(393): Google\AdsApi\AdWords\AdWordsSessionBuilder->validate()
#1 /home/ubuntu/AdsUpdater/adwords-examples-44.0.0/examples/AdWords/v201809/Reporting/DownloadCriteriaReportWithSelector.php(106): Google\AdsApi\AdWords\AdWordsSessionBuilder->build()
#2 /home/ubuntu/AdsUpdater/adwords-examples-44.0.0/examples/AdWords/v201809/Reporting/DownloadCriteriaReportWithSelector.php(116): Google\AdsApi\Examples\AdWords\v201809\Reporting\DownloadCriteriaReportWithSelector::main()
#3 {main}
  thrown in /home/ubuntu/AdsUpdater/adwords-examples-44.0.0/vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsSessionBuilder.php on line 463

```
My adsapi_php.ini is located in /home/ and I have already initialized my dev token, id, secret etc. Why would this error be happening if I have the adsapi_php.ini initialized and in the home directory?

This is my adsapi_php.ini: 
```
[ADWORDS]
; Required AdWords API properties. Details can be found at:
; https://developers.google.com/adwords/api/docs/guides/basic-concepts#soap_and_xml
developerToken = "xxxxx"
clientCustomerId = "xxxxx"

; Optional. Set a friendly application name identifier.
; userAgent = "INSERT_USER_AGENT_HERE"

; Optional additional AdWords API settings.
; endpoint = "https://adwords.google.com/"
; isPartialFailure = false

; Optional setting for utility usage tracking in the user agent in requests.
; Defaults to true.
; includeUtilitiesInUserAgent = true

[ADWORDS_REPORTING]
; Optional reporting settings.
; isSkipReportHeader = false
; isSkipColumnHeader = false
; isSkipReportSummary = false
; isUseRawEnumValues = false

[OAUTH2]
; Required OAuth2 credentials. Uncomment and fill in the values for the
; appropriate flow based on your use case. See the README for guidance:
; https://github.com/googleads/googleads-php-lib/blob/master/README.md#getting-started

; For installed application or web application flow.
clientId = "xxxxx"
clientSecret = "xxxxx"
refreshToken = "xxxxx"
; For service account flow.
; jsonKeyFilePath = "INSERT_ABSOLUTE_PATH_TO_OAUTH2_JSON_KEY_FILE_HERE"
; scopes = "https://www.googleapis.com/auth/adwords"
; impersonatedEmail = "INSERT_EMAIL_OF_ACCOUNT_TO_IMPERSONATE_HERE"

[SOAP]
; Optional SOAP settings. See SoapSettingsBuilder.php for more information.
; compressionLevel = <COMPRESSION_LEVEL>

[CONNECTION]
; Optional proxy settings to be used by requests.
; If you don't have username and password, just specify host and port.
; proxy = "protocol://user:pass@host:port"
; Enable transparent HTTP gzip compression for all reporting requests.
; enableReportingGzip = false

[LOGGING]
; Optional logging settings.
; soapLogFilePath = "path/to/your/soap.log"
; soapLogLevel = "INFO"
; reportDownloaderLogFilePath = "path/to/your/report-downloader.log"
; reportDownloaderLogLevel = "INFO"
; batchJobsUtilLogFilePath = "path/to/your/bjutil.log"
; batchJobsUtilLogLevel = "INFO"
```

**Comment by spaldingl** [comment]
So it seems that the reason I was getting the error was due to me thinking the home directory was /home/ when it was actually /home/ubuntu/

**Comment by SToneANGE** [comment]
How you were caught up in it please ?
