### ISSUE TITLE
Adgroup performance report does not work with proxy

### ISSUE THREAD

**Issue by azarecki** [googleads/googleads-php-lib#658]
I am having some trouble with downloading one of the Adwords reports, I hope you can help me with it.

**Background**:

After updating to a newer version of cURL (7.29.0 -> 7.61.1) `ADGROUP_PERFORMANCE_REPORT` stopped working with proxy. Other reports/examples, like GetCampaigns, works fine.

**Steps to reproduce**:
* Download 46.2.0 examples 
* Fill adsapi_php.ini and set proxy like this (remember to set user and password):
```
[CONNECTION]
proxy = "user:pass@tinyproxy:8888"
```
* Run ParallelReportDownload example

**Result**:

```
Downloading reports for 1 managed customers.
PHP Fatal error:  Uncaught RuntimeException: Error creating resource: [message] fopen(): php_network_getaddresses: getaddrinfo failed: Name does not resolve
[file] /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324
[message] fopen(https://adwords.google.com/api/adwords/reportdownload/v201809): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name does not resolve
[file] /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php
[line] 324 in /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php:253
Stack trace:
#0 /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(335): GuzzleHttp\Handler\StreamHandler->createResource(Object(Closure))
#1 /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php(52): GuzzleHttp\Handler\StreamHandler->createStream(Object(GuzzleHttp\Psr7\Request), Array)
#2 /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/Proxy in /var/app/misc/googleadstest/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php on line 66
```

I was curious what address it tries to resolve so I listen on DNS queries:
```
$ tcpdump -i lo eth0 port 53 -vv

13:05:24.055651 IP (tos 0x0, ttl 64, id 48596, offset 0, flags [DF], proto UDP (17), length 50)
    127.0.0.11.53 > localhost.58351: [bad udp cksum 0xfe3b -> 0xdb7c!] 54946 NXDomain q: A? user. 0/0/0 (22)
13:05:24.163592 IP (tos 0x0, ttl 64, id 48608, offset 0, flags [DF], proto UDP (17), length 125)
    127.0.0.11.53 > localhost.58351: [bad udp cksum 0xfe86 -> 0x0f7d!] 55164 NXDomain q: AAAA? user. 0/1/0 ns: . SOA a.root-servers.net. nstld.verisign-grs.com. 2020042000 1800 900 604800 86400 (97)
```

It wrongly parses the proxy setting and tries to resolve the username of the proxy user as a proxy domain. I tried setting the proxy protocol to `tcp` or `http` but without success.

**The cause**:

I did a lot of debugging and it looks like guzzle does not support streaming with proxy right now. I created an issue on guzzle GH page, but no one responded: https://github.com/guzzle/guzzle/issues/2616

I managed to get it working by **manually disabling streaming** in ReportDownloader (set to false) [here](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/AdWords/Reporting/v201809/ReportDownloader.php#L200).
<br/><br/>
Can you replicate the issue? Is some additional configuration is necessary that I'm not aware of? Do you have an idea how we can fix it?

Stay safe and healthy,
Adam

**Comment by fiboknacky** [comment]
Hello Adam,

Unfortunately, I don't have a proxy that I can use immediately to test this, but provided that we've not changed the logic of handling proxy settings for very long time, what you've found so far is highly like true. 
As the component affecting this lies in Guzzle, filing a bug on Guzzle GitHub page would be the best thing I'd do too.

Best,
Knack

**Comment by azarecki** [comment]
Hi Knack,

I filled a bug on Guzzle, but it looks like no one is interested in it. Would it be possible to disable the streaming in `googleads-php-lib`? Or make it configurable?

If you want to play with the proxy I can prepare a simple docker-compose with `googleads-php-lib` and some proxy (I used `tinyproxy` for my testing). 

Adam

**Comment by fiboknacky** [comment]
Hi Adam,

That would be helpful a lot. :)
I can modify the code to enable users to configure the `STREAM` setting too, but speaking honestly, it'd take some time due to other work.

Best,
Knack

**Comment by PierrickVoulet** [comment]
Closing this issue due to inactivity, feel free to reopen if it is still ongoing.

**Comment by PierrickVoulet** [comment]
Closing this due to inactivity and because it is obsolete now that AdWords API is sunset.
