### ISSUE TITLE
Local WSDLs bundled with this library were not found.

### ISSUE THREAD

**Issue by robgha01** [googleads/googleads-php-lib#663]
I upgraded this library from a old version to a new one and tested on my local environment it all works there. However when i push this to our live server i get this error message
```
Local WSDLs bundled with this library were not found.
in /blablabla/vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php:78
```
Im running with the latest version and dide a upgrade from 33.1.0 im baffled on how to solve this... any help is greatly appreciated.

The resources with wsdls folder and all its files is also on the server in the library map.
It seams to me that the wsdls code above is not even hit on my local environment but is at the live one what is the purpose of the wsdls and is it possible to disable it for the system to start working ?

Stacktrace
```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(1024, 'Local WSDLs bun...', '/home/forge/dgt...', 78, Array)
#1 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClient.php(78): trigger_error('Local WSDLs bun...', 1024)
#2 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/v201802/o/TargetingIdeaService.php(131): Google\AdsApi\Common\AdsSoapClient->__construct('https://adwords...', Array)
#3 [internal function]: Google\AdsApi\AdWords\v201802\o\TargetingIdeaService->__construct(Array)
#4 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/Util/Reflection.php(43): ReflectionClass->newInstanceArgs(Array)
#5 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/Common/AdsSoapClientFactory.php(89): Google\AdsApi\Common\Util\Reflection->createInstance('Google\\AdsApi\\A...', Array)
#6 /vendor/googleads/googleads-php-lib/src/Google/AdsApi/AdWords/AdWordsServices.php(60): Google\AdsApi\Common\AdsSoapClientFactory->generateSoapClient(Object(Google\AdsApi\AdWords\AdWordsSession), Object(Google\AdsApi\AdWords\AdWordsHeaderHandler), Object(Google\AdsApi\AdWords\AdWordsServiceDescriptor))
#7 /app/Jobs/ReverseKeywordMap/GetSearchVolume.php(74): Google\AdsApi\AdWords\AdWordsServices->get(Object(Google\AdsApi\AdWords\AdWordsSession), 'Google\\AdsApi\\A...')
#8 [internal function]: App\Jobs\ReverseKeywordMap\GetSearchVolume->handle()
#9 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#12 /vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#13 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#14 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ReverseKeywordMap\GetSearchVolume))
#15 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ReverseKeywordMap\GetSearchVolume))
#16 /vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ReverseKeywordMap\GetSearchVolume), false)
#18 /vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#19 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(322): Illuminate\Queue\Jobs\Job->fire()
#20 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(272): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#21 /vendor/laravel/framework/src/Illuminate/Queue/Worker.php(118): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#22 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Worker->daemon('redis', 'adwords', Object(Illuminate\Queue\WorkerOptions))
#23 /vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'adwords')
#24 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#25 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#26 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#27 /vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#28 /vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#29 /vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#30 /vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /vendor/symfony/console/Application.php(865): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

When i copy the old version over the error goes away but then i get the depreciation error instead. 
PHP version 7.2 hosted on laravel forge

**Comment by fiboknacky** [comment]
What version have you upgraded to? And what the **API** version are you using?

**Comment by robgha01** [comment]
Im upgrading from 33.1.0 to 46.2.1 and the api version im upgrading from v201802 to v201809
the version we are using is "v201809"

**Comment by robgha01** [comment]
I checked the files and thay are there 
![image](https://user-images.githubusercontent.com/362726/82316284-de4a2280-99cc-11ea-8e5d-2ac5a3408b0f.png)

I even removed the vendor map composer lock file and installed again i dide also clear the composer cache and any cache i could find in the system also searched all project code for the old version and none found still it shows up in the stacktrace. took the artisan down prior to this still no change. one good thing is the application died after i removed the vendor folder so it at least reads from that folder xD

**Comment by fiboknacky** [comment]
I don't quite get what you mentioned in the last paragraph.
Could you provide more information?
*  Do you run your application using Laravel? 
*  Do you mean you still get that notice error? Can you try debugging around [this line](https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsSoapClient.php#L75)? How are the files located?  If the files are correctly placed, that line should return something.

**Comment by robgha01** [comment]
Oh my god! i managed to fix it im not sure what fixed it but i think it had a old version that it were using somehow its strange as some libs where used in the vendor map when some were not "this one" anyhow you helped me by pushing my eyes on that version miss 🥇
