### ISSUE TITLE
Fatal Error: GuzzleHttp\Exception\ClientException

### ISSUE THREAD

**Issue by sultanboss** [googleads/googleads-php-lib#688]
Hello,

My setup was working fine and suddenly started to see this issue. I have not touched anything for the last one week. Everything was working fine. 

```
Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://oauth2.googleapis.com/token` resulted in a `429 Too Many Requests` response: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html> <head><meta http-equiv="content-type" content="te (truncated...) in /var/www/html/wp-content/plugins/prebid-plus/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113 Stack trace: #0 /var/www/html/wp-content/plugins/prebid-plus/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL) #1 /var/www/html/wp-content/plugins/prebid-plus/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response)) #2 /var/www/html/wp-content/plugins/prebid-plus/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL) #3 /var/www/html/wp-conten in /var/www/html/wp-content/plugins/prebid-plus/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

**Comment by sultanboss** [comment]
I think this is related to Google service being down. It seems many google services are down.

**Comment by fiboknacky** [comment]
It could be. Could you try again a day or two later?

**Comment by sultanboss** [comment]
Yes, it is. I am closing it now.
